services:
  app:
    build:
      args:
        user: crud
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: crud/laravel-api
    container_name: crud-api
    working_dir: /var/www/
    volumes:
      - ./:/var/www/
      - ./storage:/var/www/storage
    restart: unless-stopped
    networks:
      - docker-laravel

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "81:81"
    volumes:
      - ./:/var/www/
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - docker-laravel

  pgsql:
    image: postgres:12.17
    container_name: pgsql
    restart: always
    ports:
      - "5431:5432"
    volumes:
      - ./.docker/postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - docker-laravel

  # pgadmin:
  #   depends_on:
  #     - pgsql
  #   image: dpage/pgadmin4
  #   container_name: pgadmin
  #   restart: always
  #   ports:
  #     - "8080:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
  #   networks:
  #     - docker-laravel

  # minio:
  #   image: minio/minio
  #   container_name: minio
  #   command: server /data --console-address ":9701"
  #   restart: always
  #   environment:
  #     MINIO_ROOT_USER: minioadmin
  #     MINIO_ROOT_PASSWORD: minioadmin
  #   volumes:
  #     - ./minio_data:/data
  #   ports:
  #     - "9700:9700"
  #     - "9701:9701"
  #   networks:
  #     - docker-laravel

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6377:6379"
    networks:
      - docker-laravel

networks:
  docker-laravel:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"
